
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black']

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [ '--max-line-length=100', '--ignore=E203,W503']
        exclude: ^[^\/]+\/migrations\/
        # extend-ignore: E203, W503

  - repo: local
    hooks:
      - id: django-check
        name: Django Check
        entry: python manage.py check
        language: system
        pass_filenames: false
        types:
          - python

      - id: run-tests
        name: Run Tests
        entry: coverage run --rcfile=.coveragerc manage.py test
        language: system
        pass_filenames: false
        types:
          - python

      - id: coverage-report
        name: Coverage Report
        entry: coverage report --fail-under=20 --show-missing
        language: system
        pass_filenames: false
        types:
          - python
